use_frameworks!
 
platform :ios, '15.0'
 
target 'credenzapassport_Example' do
  pod 'credenzapassport', :path => '../../passport-pod'
  target 'credenzapassport_Tests' do
    inherit! :search_paths
    
  end
end
 
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        end
    end
end
