use_frameworks!

platform :ios, '15.0'

target 'credenzapassport_Example' do
  pod 'credenzapassport', :path => '../../passport-pod'
  target 'credenzapassport_Tests' do
    inherit! :search_paths
    
  end
end
